version: 2.1
orbs:
  docker: circleci/docker@2.1.2

jobs:
  Fetch-remote-files:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: 
          name: checking out the code
          command: |
            echo 'Hello World!'
            ls -al

  Using-Node:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: Running the Node Container
          command: |
            node -v

  Build-and-push-docker-image:
    docker:
      - image: cimg/base:stable
    steps:
      - run: 
          command: |
           echo $DOCKER_HUB_USER
           echo $DOCKER_HUB_PASSWORD
      - docker/check:
          docker-username: DOCKER_HUB_USER 
          docker-password: DOCKER_HUB_PASSWORD 
          use-docker-credentials-store: false
      - docker/build:
          image: monsteralab-auth
          path: ./Auth/ 
      - docker/push:
          image: monsteralab-auth  

workflows:
  building-monsteralab:
    jobs:
      - Fetch-remote-files
      - Using-Node:
          requires:
            - Fetch-remote-files
      - Build-and-push-docker-image:
          requires:
            - Using-Node