version: 2.1
orbs:
  docker: circleci/docker@2.1.2

jobs:
  Fetch-remote-files:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: 
          name: checking out the code
          command: |
            echo 'Hello World!'
            ls -la ./Auth

  Using-Node:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: Running the Node Container
          command: |
            node -v

  Build-and-push-docker-image:
    executor: docker/docker
    steps:
      - checkout
      - docker/check:
          docker-username: DOCKER_HUB_USER 
          docker-password: DOCKER_HUB_PASSWORD 
          use-docker-credentials-store: false
      - docker/install-docker-tools


workflows:
  building-monsteralab:
    jobs:
      - Fetch-remote-files
      - Using-Node:
          requires:
            - Fetch-remote-files
      - Build-and-push-docker-image:
          requires:
            - Using-Node
      - docker/publish:
          image: monsteralab-auth
          docker-username: DOCKER_HUB_USER 
          docker-password: DOCKER_HUB_PASSWORD 
          path: ./Auth 