version: 2.1
orbs:
  docker: circleci/docker@2.1.2

jobs:
  Fetch-remote-files:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: 
          name: checking out the code
          command: |
            echo 'Hello World!'
            ls -al

  Using-Node:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: Running the Node Container
          command: |
            node -v

  Build-and-push-docker-image:
    docker:
      - image: cimg/base:stable
    steps:
      - docker/check
      - docker/build:
          image: monsteralab-auth 
      - docker/push:
          image: monsteralab-auth  

  push-to-dockerhub:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    steps:
    

workflows:
  building-monsteralab:
    jobs:
      - Fetch-remote-files
      - Using-Node:
          requires:
            - Fetch-remote-files
      - Build-docker-image:
          requires:
            - Fetch-remote-files
            - Using-Node